import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { createAdminClient } from '@/lib/supabase/server';
import { sendCredentialsEmail } from '@/lib/email';
import bcrypt from 'bcryptjs';
import { randomUUID } from 'crypto';

export async function GET(request: NextRequest) {
  try {
    const session = await auth();
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const userRole = (session.user as any).role;

    // Only admin and manager can view agents
    if (userRole !== 'admin' && userRole !== 'manager') {
      return NextResponse.json(
        { error: 'Forbidden' },
        { status: 403 }
      );
    }

    const adminClient = createAdminClient();

    const { data: agents, error } = await adminClient
      .from('profiles')
      .select(`
        id, 
        name, 
        email, 
        phone, 
        role, 
        employee_id,
        address,
        created_at,
        created_by,
        creator:created_by(name, role, employee_id)
      `)
      .eq('role', 'agent')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching agents:', error);
      return NextResponse.json(
        { error: 'Failed to fetch agents' },
        { status: 500 }
      );
    }

    // Format the response to include creator information
    const formattedAgents = agents?.map(agent => {
      const creator = Array.isArray(agent.creator) ? agent.creator[0] : agent.creator;
      return {
        ...agent,
        created_by_name: creator?.name || null,
        created_by_role: creator?.role || null,
        created_by_employee_id: creator?.employee_id || null,
      };
    }) || [];

    return NextResponse.json({ agents: formattedAgents });
  } catch (error) {
    console.error('Agents GET error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    
    if (!session?.user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const userRole = (session.user as any).role;

    // Admins can create agents/managers, business partners can only create agents
    if (!['admin', 'business_partner'].includes(userRole)) {
      return NextResponse.json(
        { error: 'Forbidden - Only admins and business partners can create staff accounts' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { name, email, phone, password, role = 'agent', address, created_by } = body;

    // Business partners can only create agents, not managers
    if (userRole === 'business_partner' && role !== 'agent') {
      return NextResponse.json(
        { error: 'Business partners can only create agent accounts' },
        { status: 403 }
      );
    }

    // Validate role
    if (role !== 'agent' && role !== 'manager') {
      return NextResponse.json(
        { error: 'Invalid role. Must be either "agent" or "manager"' },
        { status: 400 }
      );
    }

    // Validate required fields
    if (!name || !email || !phone || !password || !address) {
      return NextResponse.json(
        { error: 'Missing required fields (name, email, phone, address, password required)' },
        { status: 400 }
      );
    }

    // Validate password strength
    if (password.length < 8) {
      return NextResponse.json(
        { error: 'Password must be at least 8 characters long' },
        { status: 400 }
      );
    }

    const adminClient = createAdminClient();

    // Check if user already exists
    const { data: existingUser } = await adminClient
      .from('profiles')
      .select('id')
      .eq('email', email)
      .single();

    if (existingUser) {
      return NextResponse.json(
        { error: 'This email is already registered' },
        { status: 400 }
      );
    }

    // Hash password
    const passwordHash = await bcrypt.hash(password, 10);

    // Create staff profile (employee_id will be auto-generated by trigger)
    const staffId = randomUUID();
    const { data: staff, error: createError } = await adminClient
      .from('profiles')
      .insert({
        id: staffId,
        email,
        name,
        phone,
        address,
        role: role,
        password_hash: passwordHash,
        created_by: created_by || null,
        enable_2fa: false,
      })
      .select('id, name, email, phone, address, role, employee_id, created_at')
      .single();

    if (createError) {
      console.error('Error creating staff:', createError);
      return NextResponse.json(
        { error: `Failed to create ${role} account` },
        { status: 500 }
      );
    }

    const loginUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/login`;

    try {
      await sendCredentialsEmail({
        to: email,
        name,
        username: name,
        password,
        role,
        loginUrl,
      });
    } catch (emailError: any) {
      console.error('Error sending credentials email:', emailError);
    }

    return NextResponse.json({
      staff,
      agent: staff,
      email_notice: 'Credentials email was attempted. If email is not configured, check server logs for the preview.',
    }, { status: 201 });
  } catch (error: any) {
    console.error('Staff creation error:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}
